# Generated by Django 5.1.2 on 2024-10-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("juba", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicetype",
            name="index",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="servicetype",
            name="is_top",
            field=models.BooleanField(default=False),
        ),
    ]
