# Generated by Django 5.1.2 on 2024-10-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("juba", "0002_servicetype_index_servicetype_is_top"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicetype",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="service_type/", verbose_name="Photo"
            ),
        ),
    ]
