# Generated by Django 5.1.2 on 2024-10-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("juba", "0003_alter_servicetype_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="detail_description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="services",
            name="detail_sub_description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="services",
            name="detail_title",
            field=models.CharField(max_length=512, null=True),
        ),
    ]
