# Generated by Django 5.1.2 on 2024-10-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("juba", "0004_services_detail_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="detail_sub_title",
            field=models.CharField(max_length=512, null=True),
        ),
    ]
