# Generated by Django 5.1.2 on 2024-10-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("juba", "0005_services_detail_sub_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="staticphoto",
            name="background_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="team/background",
                verbose_name="Background Image",
            ),
        ),
    ]
