# Generated by Django 5.1.2 on 2024-10-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("juba", "0006_staticphoto_background_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="works",
            name="short_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
