# Generated by Django 5.1.2 on 2024-10-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("juba", "0010_remove_hashtags_title_af_remove_hashtags_title_ar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="latitude",
            field=models.CharField(max_length=64, verbose_name="Latitude"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="longitude",
            field=models.CharField(max_length=64, verbose_name="Longitude"),
        ),
    ]
