# Generated by Django 5.1.2 on 2025-02-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("juba", "0011_alter_contact_latitude_alter_contact_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="seotext",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="seotext",
            name="description_uz",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="seotext",
            name="keywords_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Keywords"),
        ),
        migrations.AddField(
            model_name="seotext",
            name="keywords_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Keywords"),
        ),
        migrations.AddField(
            model_name="seotext",
            name="title_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="seotext",
            name="title_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
    ]
