# Generated by Django 5.1.2 on 2024-10-30 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("order", models.PositiveIntegerField(default=1, verbose_name="Order")),
            ],
        ),
        migrations.CreateModel(
            name="ModelOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(choices=[], max_length=200, verbose_name="Title"),
                ),
                ("app_label", models.CharField(default="auth", max_length=200)),
                ("order", models.PositiveIntegerField(default=1, verbose_name="Order")),
                (
                    "section",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="setorder.apporder",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
            },
        ),
    ]
